### ISSUE TITLE
在编辑器里输入“如果”两字，就会弹出输出面板

### ISSUE THREAD

**Issue by wisz** [EmmyLua/VSCode-EmmyLua#10]
只要在编辑器里输入“如果”两个字，就会弹出输出面板窗口，如果下图，
![1](https://user-images.githubusercontent.com/11922166/50273049-7eb4b400-0474-11e9-9bc3-e757e66f5efd.png)

**Comment by tangzx** [comment]
这个也是版本问题，已经修了。
