### ISSUE TITLE
settings.json的emmylua.colors.global会使lua标准库颜色设置无效

### ISSUE THREAD

**Issue by yuanzhifei89** [EmmyLua/VSCode-EmmyLua#103]
vscode版本1.68.0, 插件版本0.4.19，设置了emmylua.colors.global后，"scope":"support.function.lua"和"scope":"support.function.library.lua"设置的foreground颜色都无效

**Comment by CppCXY** [comment]
该项设置会强行对目标代码染色，不希望有的话删掉这项配置的值
