### ISSUE TITLE
Failed to start "EmmyLua" language server!

### ISSUE THREAD

**Issue by nneesshh** [EmmyLua/VSCode-EmmyLua#11]
Hi, all, Emmylua is so good.
The breakpoint worked, but it tips an message on the right-bottom corner:
   
   **Failed to start "EmmyLua" language server! Launching server using command C:\Program Files\Java\jdk1.8.0_40\bin\java.exe failed.**
  Try again

Should I install the java.exe manually?

**Comment by tangzx** [comment]
> Failed to start "EmmyLua" language server! Launching server using command C:\Program Files\Java\jdk1.8.0_40\bin\java.exe failed.

Does `C:\Program Files\Java\jdk1.8.0_40\bin\java.exe` exist? EmmyLua-LS(language server) runs on java. Check your `JAVA_HOME` environment variable

> file not found:=headers metatable
file not found:=ngx.socket.connect
file not found:=coroutine.wrap
file not found:=_G write guard

Just care about the files you want to debug

**Comment by nneesshh** [comment]
hi, @tangzx , thanks for you nice answer.
I just install the EmmyLua extension throug vscode store, and I did not install any java sdk in my computer. I will try to install one manully later.

Another question:
Though the breakpoint already worked for me, does it means that I could ignore the java sdk with no risk?

**Comment by tangzx** [comment]
EmmyLua provides two features: Lua editor & Lua debugger.
The editor which is the main feature of emmylua depends on java, but the debugger does't.  Strongly recommend you install the java to enable editor.

see [IntelliJ-EmmyLua](https://github.com/EmmyLua/IntelliJ-EmmyLua) and [Doc](https://emmylua.github.io/)
The annotations also available for VSCode-EmmyLua
