### ISSUE TITLE
平时用XLua+Unity，请问CS.UnityEngine.XXX这种可以不报警告吗？或者可以自定义警告规则

### ISSUE THREAD

**Issue by zouchanglin** [EmmyLua/VSCode-EmmyLua#117]
平时用XLua+Unity，请问CS.UnityEngine.XXX这种可以不报警告吗？或者可以自定义警告规则
<img width="322" alt="image" src="https://user-images.githubusercontent.com/29838710/212465579-309d6066-20a3-4620-b06b-4593005c807a.png">

**Comment by CppCXY** [comment]
vscode emmylua 没有警告，这是其他插件爆的，另外你可以试试emmylua-unity插件

**Comment by zouchanglin** [comment]
好的，感谢建议~

**Comment by zouchanglin** [comment]
刚才把EmmyLua禁用了，没有警告，但是打开就有了，说明还是EmmyLua报的警告～ 请问能自定义警告规则吗？

**Comment by CppCXY** [comment]
EmmyLua 默认没有警告, 可能你安装了sumneko Lua 或者luahelper
