### ISSUE TITLE
Project loading time?

### ISSUE THREAD

**Issue by faseceroo** [EmmyLua/VSCode-EmmyLua#121]
Hi! I have a lua project with generated intellisense with around 12000 .lua files. This same project loads almost instantly on EmmyLua Intellij but it takes around 30-40 seconds in EmmyLua VS Code with no other extension. Wondering if this is some VS Code's limitation or the delay resides somewhere else.

**Comment by CppCXY** [comment]
vscode-emmylua does not store indexes

**Comment by faseceroo** [comment]
I see. No big deal anyway. You know, your extension is a real time saver with Field Validation and Parameter Validation, it prevents from making a LOT of mistakes while coding because lua don't have type checking. Also it allows me to make code changes in a breeze. Thanks a lot.
