### ISSUE TITLE
Function parameter hint?

### ISSUE THREAD

**Issue by faseceroo** [EmmyLua/VSCode-EmmyLua#122]
Is it possible to show parameter types in vs code? I see it can be done in Intellij. In vs code we have

![image](https://user-images.githubusercontent.com/93630866/221355274-4434583c-3b43-4681-b809-5adcdbe44c3f.png)

Enable param hint = activates the underlined texts in green
Variable parameter hint = ?

I guess it's an option to show the type of the Anim variable which is UAnimInstance but it doesn't seem to work.

**Comment by CppCXY** [comment]
vscode and intellij are different implementations about inlay hint.I'm currently working on a new language server and may not have time to deal with vscode-emmylua

**Comment by faseceroo** [comment]
No worries, both extensions are great. I'm trying to use Intellij which seems to have erverything I need. Thanks gl with your project!
