### ISSUE TITLE
断点命中、单步调试很卡，cpu占用高

### ISSUE THREAD

**Issue by stzb321** [EmmyLua/VSCode-EmmyLua#125]
命中断点时，从任务管理器里看到是vscode的rg.exe占用cpu很高，看起来像是在查找堆栈每层的源文件
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/7479352/7e2f1736-6539-4479-8dff-30d3cfd90017)

每次命中断点都要卡大概5-10秒。

版本: 1.78.2 (system setup)
提交: b3e4e68a0bc097f0ae7907b217c1119af9e03435
日期: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: Yes

emmylua插件版本：0.5.14

补充：发现ctrl+P查找文件，cpu也是会升到100%，是项目太大，文件太多了吗。

**Comment by CppCXY** [comment]
查找文件是使用的vscode本身的机制, rp是vscode内建的一个非常快的查找工具, 他不应该这么慢, 或许你可以报给vscode官方, 或者和你的文件关联有关, 或者你只打开只包含lua的目录试试
