### ISSUE TITLE
怎么关掉调试器功能

### ISSUE THREAD

**Issue by senlinding** [EmmyLua/VSCode-EmmyLua#126]
版本：v0.5.14
目前是使用LuaPanda调试，使用emmylua进行代码跳转。
但是创建调试器时，emmylua会成为唯一选择，无法选择LuaPanda调试。怎么关掉emmylua调试器功能
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/4864830/5b5d315e-f318-42c9-ad97-4c25af322b87)

**Comment by CppCXY** [comment]
没有，不能关，这应该是vscode的问题或者luapanda的问题。比如安装lua debug插件也是可以显示在这里的。你可以试试关掉emmylua插件看看会不会弹出luapanda。

**Comment by senlinding** [comment]
> LuaPanda

@CppCXY 禁用LuaPanda后就能弹出luapanda了

**Comment by CppCXY** [comment]
如果emmylua调试器不想用, 建议你直接卸载emmylua, 用Lua Language Server. 他没有调试器部分.而且很多功能是更强的

**Comment by senlinding** [comment]
> emmylua

嗯。了解，emmylua体验还是挺不错的。调试这个问题我自己注意一下也还行。多谢
