### ISSUE TITLE
项目路径中包括特殊符号则无法跳转

### ISSUE THREAD

**Issue by Triple-Z** [EmmyLua/VSCode-EmmyLua#127]
假设项目路径为 `D:\Code\#hello\project-root` ，则 EmmyLua 只能跳转至 `D:\Code` 。整体路径包括 `#` 则无法跳转。

**Comment by CppCXY** [comment]
建议改名, '#'在vscode的uri中的意义是分割url和行数列数

**Comment by CppCXY** [comment]
emmylua自身的url decode无法正确解析包含 #, %, 等特殊符号的路径
