### ISSUE TITLE
vscode tolua断点调试unity时，对于lua获取的Unity控件，查看详细信息Unity就会崩溃

### ISSUE THREAD

**Issue by mnipaige** [EmmyLua/VSCode-EmmyLua#129]

**Comment by CppCXY** [comment]
你可以给我一个能复现的最小工程

**Comment by mnipaige** [comment]
Unity工程，环境以及复现操作流程都在附件里


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EmmyLua/VSCode-EmmyLua"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月10日(星期一) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EmmyLua/VSCode-EmmyLua] vscode tolua断点调试unity时，对于lua获取的Unity控件，查看详细信息Unity就会崩溃 (Issue #129)





 
你可以给我一个能复现的最小工程

**Comment by CppCXY** [comment]
没有看到, 你发给阿唐我是收不到的, 或者你加群

**Comment by CppCXY** [comment]
看到的话可以加4群: 1063151386
