### ISSUE TITLE
VScode EmmyLua 升级到0.5.17后无法调试。

### ISSUE THREAD

**Issue by MrChunYuSong** [EmmyLua/VSCode-EmmyLua#132]
--

**Comment by CppCXY** [comment]
如果你确认你知道如何调试, 自己检查是不是require失败, 这通常会因为错误的custom loader 拦截emmy_core的加载.
另外emmylua在mac上生成的cpath路径其实是 emmy/mac/{arch}/emmy_core.dylib 而不是 /?.dylib

如果你确认加载成功, 自己检查自己是不是没有地方监听端口, 通常需要要么调试器监听, 要么ide监听端口
