### ISSUE TITLE
是否有计划支持兼容luapreprocess的预处理语法

### ISSUE THREAD

**Issue by ryanrhu** [EmmyLua/VSCode-EmmyLua#135]
在项目中想使用[luapreprocess](https://github.com/ReFreezed/LuaPreprocess)实现预处理功能，实现一些代码的隔离和剔除功能。
但是这种"!"起始的标记语法和emmylua原本的语法检查，或者说原生的lua语法，是不兼容的；所以想了解一下是否有计划对这类预处理，或者类似宏的机制做语法兼容

**Comment by CppCXY** [comment]
emmylua当前的语法分析不是手写的, 很难做到自定义语法规则, 如果你不需要调试功能, 你可以使用lua-language-server(sumneko-lua) 他的插件功能可以绕过这一点, 你试着写个插件, 如果你需要调试功能, 单独的lua-debug也是不错的选项, 他是目前vscode中实现得最完整得调试器.
