### ISSUE TITLE
vscode附加调试会导致Unity崩溃

### ISSUE THREAD

**Issue by wang573287909** [EmmyLua/VSCode-EmmyLua#136]
vscode附加调试会导致Unity退出，并且unity没有崩溃日志和弹窗。

**Comment by wang573287909** [comment]
9月19更新的v0.5.19之后就出现这个问题了

**Comment by CppCXY** [comment]
0.5.18到0.5.19有两项改动:
1. 更新libuv到最新版
2. 调试器优先使用ipv6地址
除此以外没有任何改动了, 你可以下载源码编译debug版本自己调试

**Comment by wang573287909** [comment]
确实，我还原版本后还是会这样，intllij又会报non-index的错误，两个idea都无法正常工作

**Comment by CppCXY** [comment]
如果不是因为升级导致得问题,那就是你们项目新增得代码引发了调试崩溃, 你可以:
1. 给出最小复现工程
2. 进群讨论
3. 下载调试器源码自己调试.

idea得问题, 你可以升级到1.4.8不过插件商店上被撤回了
