### ISSUE TITLE
Enums with strings not working as expected on VS Code

### ISSUE THREAD

**Issue by matpratta** [EmmyLua/VSCode-EmmyLua#138]
Take the example in the official docs, I tried creating the follwing enum:
```lua
---@param event_name string | "'onStart'" | "'onStop'"
function event(event_name) end
```

When I type the `event` function, it will show the suggested values (onStart, onStop) in VS Code, but they are added without any quotation marks around. Is there any way of adding those?

**Comment by CppCXY** [comment]
please try 
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/5525b3f3-38a9-4117-bb3c-ae86ffed1526)

**Comment by CppCXY** [comment]
this feature has been completed by new language server
