### ISSUE TITLE
断点取消不了，一直存在

### ISSUE THREAD

**Issue by Var-al** [EmmyLua/VSCode-EmmyLua#139]
在使用EmmyLua进行断点时，删除断点，但是无效，跑起来还是会断点到，除非程序开启调试

**Comment by CppCXY** [comment]
不清楚你在描述怎样的情况, 在确保最新版的情况下, 有可能是你在调试时编辑了代码改变了断点行数, 遇到这种问题你可以在莫名命中的地方再打一次断点, 再删除

**Comment by Var-al** [comment]
嗷，是版本问题，谢谢答复！
