### ISSUE TITLE
Missing license file.

### ISSUE THREAD

**Issue by notpeter** [EmmyLua/VSCode-EmmyLua#143]
Which open source license are you using for this code? I assume it's MIT but didn't see anything confirming that in-repo.

**Comment by CppCXY** [comment]
I am not the original author of this project, so I should not add a license to it (if any, it should be the same as on IntelliJ)

**Comment by notpeter** [comment]
That appears to be Apache-2.0

https://github.com/EmmyLua/IntelliJ-EmmyLua/blob/master/LICENSE.txt
