### ISSUE TITLE
新版本一些问题

### ISSUE THREAD

**Issue by 37wjy** [EmmyLua/VSCode-EmmyLua#147]
项目的主要文件在 asset/lua 下, 有一些class的定义放在 .vscode 下, 其中根目录, asset/lua 被分别添加到同一工作区, 旧版本(v0.6.18)不会提示在 asset/lua 中的脚本中的某些被定义在 .vscode 中的变量不存在, 如 CS这个, 而新版本会

**Comment by CppCXY** [comment]
新版本再分析时会直接排除.vscode目录中的文件

**Comment by 37wjy** [comment]
请问是加了分析文件大小的限制吗, 我把文件删小了后, 这个全局变量就不提示不存在了

**Comment by CppCXY** [comment]
文件大小限制是1mb, 以及如果在排除目录中会在手动打开文件时解析一次, 你可以通过配置设置这些, 具体看changelog

**Comment by 37wjy** [comment]
解决了,  

新加的注释功能感觉很好,
```lua
---@generic T
---@param classname `T`
---@return T
```
但是一般项目中也会用这种形式用于继承 
```
Class("classname", base)
```
希望可以有类似的支持
```
---@generic T, B
---@param classname `T`
---@param base B
---@return T:B
function Class(classname, base) end
```

**Comment by CppCXY** [comment]
这个功能不是为了实现class函数而做的, 因为没有显式的定义类型会找不到类型定义, 类型补全也不会有他

**Comment by CppCXY** [comment]
崩溃的原因应该是library在项目内, 然后dictionary因为key重复异常了

**Comment by CppCXY** [comment]
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/e1ae8c25-7971-4c2e-a9e2-4e5b1a188308)
我这样配置是有效的

**Comment by 37wjy** [comment]
解决了, 我之前因为配了lib, crash了所以没成

希望配置文件后面可以放到.vscode下, 或者整合到setting里

**Comment by 37wjy** [comment]
注释有点bug 

```lua
    ---@type Transform
    self.transform = nil         --- aaa
    ---@type GameObject
    self.gameObject = nil          --- gameObject
    ---@type RectTransform
    self.rectTransform = nil  
```
这段代码会提示self.gameObject 的类型是RectTransform

```lua
    ---@type Transform
    self.transform = nil        
    ---@type GameObject
    self.gameObject = nil          --- gameObject
    ---@type RectTransform
    self.rectTransform = nil  
```
这个不会

<img width="357" alt="截屏2024-05-22 18 54 26" src="https://github.com/EmmyLua/VSCode-EmmyLua/assets/34015616/5916d79b-efdb-4502-9874-0c99db48d5e5">

**Comment by 37wjy** [comment]
<img width="458" alt="截屏2024-05-23 10 37 40" src="https://github.com/EmmyLua/VSCode-EmmyLua/assets/34015616/ab83b04a-1487-4e55-99e8-25929a8a5836">
这种提示刷新也有点问题, 就算改完,在git上提交了, 依旧会出现, 点了提示后会跳到git提交前的文件, 只有关了vscode, 重启服务才能解决

**Comment by 37wjy** [comment]
旧版本 使用 
```lua
---@class AAA
local AAA = Class("AAA")

local a = AAA()
```
可以将a识别为AAA这个类型, 新版本不行, 而且没发提示__call

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLuaAnalyzer/issues
我建议你每个问题发一个issue到这里
