### ISSUE TITLE
0.7版本检查速度很慢，一些设置不生效

### ISSUE THREAD

**Issue by Lance3210** [EmmyLua/VSCode-EmmyLua#148]
检查工作区内文件特别慢，关闭函数调用参数提示设置不生效，退回到0.6.18正常

**Comment by CppCXY** [comment]
插件不会读取vscode任何配置, 另外检查慢是因为depracated检查的缘故, 我知道但是暂时不想改. 之所以退回0.6.18正常, 是因为0.6.18默认使用的是java版本的语言服务, 0.7.0开始默认使用的是dotnet实现的语言服务

**Comment by ihonk** [comment]
今天刚回退0.6.18，我这项目文件几千个，0.7版本之后内存占用太大了

**Comment by CppCXY** [comment]
> 今天刚回退0.6.18，我这项目文件几千个，0.7版本之后内存占用太大了

在分析相同数量文件的情况下dotnet实现的语言服务内存占用是低于java语言服务的, 或许你以前配置过.emmy.config.json, 排除了许多文件, 而如今的语言服务并不会去读.emmy.config.json, 他有自己的配置文件.emmyrc.json 你可以看看changelog里面对他配置的描述

**Comment by unknown32767** [comment]
> > 今天刚回退0.6.18，我这项目文件几千个，0.7版本之后内存占用太大了
> 
> 在分析相同数量文件的情况下dotnet实现的语言服务内存占用是低于java语言服务的, 或许你以前配置过.emmy.config.json, 排除了许多文件, 而如今的语言服务并不会去读.emmy.config.json, 他有自己的配置文件.emmyrc.json 你可以看看changelog里面对他配置的描述

新language server不分析同一个workspace下其他文件夹的内容，尝试往.emmyrc.json的workspace.workspaceRoots、resource.paths内添加${workspace}系文件夹路径也没有作用；旧版并未作任何设置就自动分析了workspace内所有文件夹内的文件，请问这里新版应该怎么配置？

**Comment by CppCXY** [comment]
> > > 今天刚回退0.6.18，我这项目文件几千个，0.7版本之后内存占用太大了
> > 
> > 
> > 在分析相同数量文件的情况下dotnet实现的语言服务内存占用是低于java语言服务的, 或许你以前配置过.emmy.config.json, 排除了许多文件, 而如今的语言服务并不会去读.emmy.config.json, 他有自己的配置文件.emmyrc.json 你可以看看changelog里面对他配置的描述
> 
> 新language server不分析同一个workspace下其他文件夹的内容，尝试往.emmyrc.json的workspace.workspaceRoots、resource.paths内添加${workspace}系文件夹路径也没有作用；旧版并未作任何设置就自动分析了workspace内所有文件夹内的文件，请问这里新版应该怎么配置？

在多工作区的情况下只会分析第一个工作区, 如果你希望其他目录作为提示的库, 应该配置library, workspaceRoots只是用来设置require的根目录
