### ISSUE TITLE
最新版启动失败了

### ISSUE THREAD

**Issue by cjzswang5** [EmmyLua/VSCode-EmmyLua#154]
[2-EmmyLua plugin for vscode..log](https://github.com/user-attachments/files/15688840/2-EmmyLua.plugin.for.vscode.log)

好像是在根目录使用.emmyrc.json就会启动失败：
```
{
    "diagnostics": {
        "disable": [
            "undefined-global"
        ]
    }
}
```
另外想问一下 .emmyrc.json 有配置文档可以参考吗？
另外我想去掉所有下图这种行内提示要如何配置？
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/26997744/85ba04bd-1e08-42e9-8fa1-378c0eb92d2c)

**Comment by CppCXY** [comment]
没有配置文档, 你需要在.emmyrc.json里面写入:
```json
  "hint": {
    "paramHint": false,
    "indexHint": false,
    "localHint": false,
    "overrideHint": false
  }
```

**Comment by CppCXY** [comment]
至于你无法启动的问题, 是检查是否是子类型的时候发生了递归爆栈, 我晚点处理
