### ISSUE TITLE
slua无法断点

### ISSUE THREAD

**Issue by yish0000** [EmmyLua/VSCode-EmmyLua#157]
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/3023727/5b177ae1-9494-4df7-8738-d6159d5dd388)
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/3023727/ec8465be-32cc-41e8-82d8-e4e59938e735)
看着Attach到进程都正常，但断点无法触发

**Comment by yish0000** [comment]
如果PublicDelayLoadDLLs不添加lua.dll
调试器Attach进程后再运行PIE，会在加载lua.dll的时候崩溃
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/3023727/96898d18-33c3-4774-9ea4-252f307281b6)

**Comment by yish0000** [comment]
local emmy_core = require("emmy_core")
emmy_core.tcpListen('localhost', 9966)
用这种方式连接成功后也无法断点

**Comment by CppCXY** [comment]
slua的chunkname大概不符合标准的chunkname格式, 你可以打印 debug.getinfo(1).source看看, 之前slua在unity上就采用了自定义的格式. 这对于调试来讲是必要的信息一般不宜随便写. chunkname的格式就是文件路径格式, 另外如果你希望修改这个格式, 需要看看slua是如何加载lua文件的, 所谓chunkname指的就是lua_loadbuffer这些函数中的参数

**Comment by yish0000** [comment]
已解决，感谢
