### ISSUE TITLE
client: couldn't create connection to server

### ISSUE THREAD

**Issue by xiaozhi927** [EmmyLua/VSCode-EmmyLua#158]
之前使用一直没出现过这个问题，更新vscode到1.89.1后重启vscode后出现这个问题

**Comment by xiaozhi927** [comment]
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/59357648/2b7d71aa-05d7-4704-991a-0ebd2b9a2be5)
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/59357648/cb67b650-1f67-4e03-9de3-0ea8e6cc9e6b)

**Comment by CppCXY** [comment]
emmylua-unity这个插件目前是废的

**Comment by xiaozhi927** [comment]
好滴好滴，禁用掉之后正常了
