### ISSUE TITLE
无法关闭函数调用的参数提示(Param Hint)

### ISSUE THREAD

**Issue by RetuEase** [EmmyLua/VSCode-EmmyLua#159]
在设置中Emmylua > Hint: Param Hint中勾选关闭、在设置json中设置为false后仍然有函数调用的参数名提示。

尝试了重启vscode、重新加载插件、同时关闭Vararg Hint(可变参数提示)，均无法关闭函数调用的参数名提示。

**Comment by CppCXY** [comment]
所有vscode 配置对新语言服务都是无效的

**Comment by CppCXY** [comment]
> > 所有vscode 配置对新语言服务都是无效的
> 
> Emmylua > Hint: Param Hint属于扩展的配置呀，不是vscode自己的配置……

这里包含了emmylua在vscode上的配置, 因为这个配置是早期java版本语言服务所用的,目前保留仅仅是为了兼容一些使用老语言服务的用户

**Comment by CppCXY** [comment]
如果你想关掉这个, 你必须在根目录(不是在.vscode里面)创建.emmyrc.json, 然后根据补全自己写:
```json
{
  "hint": {
    "paramHint": true,
    "indexHint": true,
    "localHint": true,
    "overrideHint": true
  }
}
```
把true改为false

**Comment by RetuEase** [comment]
> 如果你想关掉这个, 你必须在根目录(不是在.vscode里面)创建.emmyrc.json, 然后根据补全自己写:
> 
> ```json
> {
>   "hint": {
>     "paramHint": true,
>     "indexHint": true,
>     "localHint": true,
>     "overrideHint": true
>   }
> }
> ```
> 
> 把true改为false

确实有效！原来是这样设计的，非常感谢你
