### ISSUE TITLE
配置的关掉未定义全局变量提示不生效

### ISSUE THREAD

**Issue by MiuraUnnchi** [EmmyLua/VSCode-EmmyLua#162]
![screenshot-20240626-114537](https://github.com/EmmyLua/VSCode-EmmyLua/assets/173868959/8f108a77-8a61-4a8f-bc27-4132610d603d)
![screenshot-20240626-114544](https://github.com/EmmyLua/VSCode-EmmyLua/assets/173868959/ecb2535e-fe34-4750-b233-734755f747b3)
是不是哪里设置有问题

**Comment by liubinseu** [comment]
undefined,单词拼写错了。 还有看文档不是应该配置在这里的吧， ./syntaxes/schema， 虽然我目前也没解决掉

**Comment by CppCXY** [comment]
配置在.vscode外面全称 `.emmyrc.json`

**Comment by CppCXY** [comment]
另外在报错的地方按ctrl . 可以弹出 
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/f050eea0-20a3-47ae-be73-ec3c1660415b)
之后可以选择最下面那个, 也会自动生成.emmyrc.json.
如果看不到这个快速修复的提示, 很可能是被垃圾国产AI软件吃掉了

**Comment by HUSTJJD** [comment]
> 另外在报错的地方按ctrl . 可以弹出 ![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/f050eea0-20a3-47ae-be73-ec3c1660415b) 之后可以选择最下面那个, 也会自动生成.emmyrc.json. 如果看不到这个快速修复的提示, 很可能是被垃圾国产AI软件吃掉了

不支持 .code-workspace 吗，如果用vscode直接打开文件夹，配置是生效的，如果用woarkspace打开多个子文件夹，.emmyrc.json与.code-workspace 同级，配置无法生效。

**Comment by CppCXY** [comment]
> > 另外在报错的地方按ctrl . 可以弹出 ![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/f050eea0-20a3-47ae-be73-ec3c1660415b) 之后可以选择最下面那个, 也会自动生成.emmyrc.json. 如果看不到这个快速修复的提示, 很可能是被垃圾国产AI软件吃掉了
> 
> 不支持 .code-workspace 吗，如果用vscode直接打开文件夹，配置是生效的，如果用woarkspace打开多个子文件夹，.emmyrc.json与.code-workspace 同级，配置无法生效。

当你项目中存在.code-workspace时, emmylua并不知道 .code-workspace这个文件在哪, vscode会把它转化为多工作区的形式上报上来, 我选择使用第一个上报的工作区的目录下的.emmyrc.json
