### ISSUE TITLE
GBK文件注释有概率显示乱码

### ISSUE THREAD

**Issue by tinymins** [EmmyLua/VSCode-EmmyLua#164]
> 注：A.lua 与 B.lua 都是 GBK 编码。

新建文件时正常：
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/76ca3e4c-ac0a-4126-8e92-7666d8585866)

保存后立马乱码：
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/b874d310-0358-498f-ae10-17c5e3dd527f)

重启编辑器，在A.lua没有打开之前，B.lua显示乱码：
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/2277a0a3-c448-43ee-acc4-4380b583bddd)

此时打开一次 A.lua 文件，再看 B.lua 的注释就正常了：
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/b5a9fd4c-3883-4378-ada8-3fd2b69b8ea7)

完整项目地址：
https://github.com/tinymins/JX3Boilerplate

**Comment by CppCXY** [comment]
vscode默认打开文件的方式是UTF8 你改过files.encoding设置没有

**Comment by CppCXY** [comment]
在vscode的工作区配置添加然后重启vscode: 
```json
    "files.encoding": "gbk"
```

**Comment by tinymins** [comment]
> 在vscode的工作区配置添加然后重启vscode:
> 
> ```json
>     "files.encoding": "gbk"
> ```

![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/41898f75-1a8d-4098-8a47-20b9d9a923c4)
有的，一直有这个设置

**Comment by tinymins** [comment]
> vscode默认打开文件的方式是UTF8 你改过files.encoding设置没有

正式因为加了设置，所以文件在每次打开后，乱码就会消失，这也是我们使用插件看到乱码时候的处理办法，按住ALT追踪过去一下，乱码就暂时消失了。

**Comment by CppCXY** [comment]
插件版本呢

**Comment by tinymins** [comment]
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/653fea84-fba5-4551-877f-c98a6311b222)
0.8.0

> 插件版本呢

**Comment by CppCXY** [comment]
我感觉是因为你没有使用setting.json的问题, 让插件没有获取编码信息:
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/40318218/e3108e69-d6e4-49c2-bd2c-4fb1448d39d9)
"好好好"是定义在另一个文件的变量,项目编码设置为GBK, 在完全重启插件后能正常提示

**Comment by tinymins** [comment]
那意思是，一定要写在 setting.json 中，而不能写在 .code-workspace 中，插件是主动去 setting.json 文件获取的编码么？

**Comment by tinymins** [comment]
> 那意思是，一定要写在 setting.json 中，而不能写在 .code-workspace 中，插件是主动去 setting.json 文件获取的编码么？

我去试试在每个文件夹下都增加一份 setting.json 试试，一个 workspace 包含了很多个文件夹，不知道这么加能不能用

![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/400ea8c3-a3e6-45b1-9c0a-da12ee8fa5af)

**Comment by tinymins** [comment]
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/520fc30a-57ad-4fd5-97b2-13fad31bab53)
实测不能生效，设置完后重启vscode，乱码依旧，看起来插件无法兼容 workspace 的编码

**Comment by CppCXY** [comment]
我clone 了你的项目, 没有看到和你一样的代码结构

**Comment by tinymins** [comment]
> 我感觉是因为你没有使用setting.json的问题, 让插件没有获取编码信息: ![image](https://private-user-images.githubusercontent.com/40318218/344090801-e3108e69-d6e4-49c2-bd2c-4fb1448d39d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjI4MjMsIm5iZiI6MTcxOTU2MjUyMywicGF0aCI6Ii80MDMxODIxOC8zNDQwOTA4MDEtZTMxMDhlNjktZDZlNC00OWMyLWJkMmMtNGZiMTQ0OGQzOWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTk5N2Q1NmRmOGVhMDU4YzJmYjMwOTIxMzE0ZTBiYmY3Njk5ZWNhZDIwMGZmMjEwMmZkNzAzNWUzYzQ0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jw_2WfVLSjBAjGuAp8sn46A1fJSEyYsUl5_laGK29QQ) "好好好"是定义在另一个文件的变量,项目编码设置为GBK, 在完全重启插件后能正常提示

以及中文似乎不能作为变量名，在我这会报错，我是注释中文
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/5ab80fe4-8f23-4207-a7f3-a2e889dc923c)

**Comment by tinymins** [comment]
> 我clone 了你的项目, 没有看到和你一样的代码结构

因为是多个仓库，您可以直接创建一个 workspace，内容：


## Boilerplate.code-workspace

```
{
	"folders": [
		{
			"path": "Boilerplate"
		}
	],
	"settings": {
		"editor.tabSize": 4,
		"editor.renderWhitespace": "all",
		"editor.insertSpaces": false,
		"files.encoding": "gbk",
		"files.autoGuessEncoding": true,
		"files.eol": "\n",
		"files.trimTrailingWhitespace": true,
		"files.trimFinalNewlines": true,
		"files.associations": {
			"*.lang": "lua",
			"*.jx3dat": "lua"
		},
		"flake8.args": [
			"--ignore=E501,E722"
		],
		"lua.targetVersion": "5.1",
		"psi-header.changes-tracking": {
			"isActive": true,
			"exclude": [
				"markdown",
				"json",
				"html",
				"vue",
				"jx3dat"
			],
			"autoHeader": "off"
		},
		"psi-header.lang-config": [{
			"language": "lua",
			"begin": "--------------------------------------------------------",
			"prefix": "-- ",
			"end": "--------------------------------------------------------",
			"blankLinesAfter": 0
		}],
		"psi-header.templates": [{
			"language": "*",
			"template": [
				"This file is part of the JX3 Plugin Project.",
				"@desc     : ",
				"@copyright: Copyright (c) 2009 Kingsoft Co., Ltd.",
			]
		}],
		"[lua]": {
			"files.encoding": "gbk",
			"files.autoGuessEncoding": false,
		},
		"[ini]": {
			"files.encoding": "gbk",
			"files.autoGuessEncoding": false,
			"files.trimFinalNewlines": false,
			"files.trimTrailingWhitespace": false,
		},
		"[markdown]": {
			"files.encoding": "utf8",
			"files.autoGuessEncoding": false,
		},
		"[python]": {
			"files.encoding": "utf8",
			"files.autoGuessEncoding": false,
		},
		"luahelper.format.extra_sep_at_table_end": true,
		"luahelper.Warn.CheckLocalNoUse": true,
		"luahelper.Warn.CheckNoUseAssign": true,
		"luahelper.base.ignoreFileOrDir": [
			"\\.vscode/"
		],
		"luahelper.base.ignoreFileOrDirError": [
			"\\.vscode/",
			"zhtw\\.jx3dat",
			"dist/",
			"src\\..*\\.lua",
			".*\\.min\\.jx3dat"
		],
		"cSpell.words": [
			"Sysmsg",
			"wstring"
		],
	},
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"type": "LuaHelper-Debug",
				"request": "launch",
				"name": "LuaHelper-Attach",
				"description": "通用模式,通常调试项目请选择此模式",
				"cwd": "${workspaceFolder:Boilerplate}",
				"luaFileExtension": "",
				"connectionPort": 8828,
				"stopOnEntry": true,
				"useCHook": true,
				"autoPathMode": true
			},
			{
				"type": "LuaHelper-Debug",
				"request": "launch",
				"name": "LuaHelper-DebugFile",
				"description": "独立文件调试模式",
				"luaPath": "",
				"packagePath": [],
				"luaFileExtension": "",
				"connectionPort": 8828,
				"stopOnEntry": true,
				"useCHook": true
			}
		]
	}
}

```

**Comment by tinymins** [comment]
实测，在完全相同环境下，单独启用腾讯的 LuaHelper，Tip不会展示乱码，单独启用 EmmyLua 展示乱码，同时启用展示一条乱码一条不乱码

单独 LuaHelper
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/7b6700fe-3440-468e-b037-1d3bba0de6e4)

单独 EmmyLua
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/32929bc4-8ae0-4809-b72a-29178920d18d)

同时启用
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/1808990/f3ade052-ca3e-4ebf-b082-42499b76ecff)

**Comment by tinymins** [comment]
~请问有 donate 方式吗，我在 README 中没有看到，我也是做开源插件的（只不过我的是游戏插件），感谢抽空处理问题，想请喝奶茶~

找到了，支付宝投币100元 😸

**Comment by CppCXY** [comment]
> ~请问有 donate 方式吗，我在 README 中没有看到，~ 我也是做开源插件的（只不过我的是游戏插件），感谢抽空处理问题，想请喝奶茶
> 
> 找到了，支付宝投币100元 😸

你做的好, 但我实际上并不能收到. 这是以前emmylua作者tangzx的链接, 而我并不是他.

你的问题是, 由于当前实现的问题, 你没有创建.emmyrc.json所以gbk的配置无效

**Comment by tinymins** [comment]
> > ~请问有 donate 方式吗，我在 README 中没有看到，~ 我也是做开源插件的（只不过我的是游戏插件），感谢抽空处理问题，想请喝奶茶
> > 找到了，支付宝投币100元 😸
> 
> 你做的好, 但我实际上并不能收到. 这是以前emmylua作者tangzx的链接, 而我并不是他.
> 
> 你的问题是, 由于当前实现的问题, 你没有创建.emmyrc.json所以gbk的配置无效

感谢，请问您有donate方式吗，愿意再请一杯下午茶。

乱码看起来是腾讯的会自动识别编码，而EmmyLua需要手动指定，腾讯的LuaHelper我没有做特别设置。

**Comment by CppCXY** [comment]
> 感谢，请问您有donate方式吗，愿意再请一杯下午茶。
不用了, 感谢他就行了. 
> 乱码看起来是腾讯的会自动识别编码，而EmmyLua需要手动指定，腾讯的LuaHelper我没有做特别设置。
乱码问题是因为: 没有添加配置文件导致后续处理被跳过了, 本质上也不需要配置. 但是emmylua配置项非常多最好还是配置下, 当前最快的修复方法是在首个工作区内创建一个空的.emmyrc.json文件

**Comment by CppCXY** [comment]
> > 感谢，请问您有donate方式吗，愿意再请一杯下午茶。
> 
> 不用了, 感谢他就行了.
> 
> > 乱码看起来是腾讯的会自动识别编码，而EmmyLua需要手动指定，腾讯的LuaHelper我没有做特别设置。
> 
> 乱码问题是因为: 没有添加配置文件导致后续处理被跳过了, 本质上也不需要配置. 但是emmylua配置项非常多最好还是配置下, 当前最快的修复方法是在首个工作区内创建一个空的.emmyrc.json文件

貌似还不行? 等会研究下

**Comment by tinymins** [comment]
> > > 感谢，请问您有donate方式吗，愿意再请一杯下午茶。
> > 
> > 
> > 不用了, 感谢他就行了.
> > > 乱码看起来是腾讯的会自动识别编码，而EmmyLua需要手动指定，腾讯的LuaHelper我没有做特别设置。
> > 
> > 
> > 乱码问题是因为: 没有添加配置文件导致后续处理被跳过了, 本质上也不需要配置. 但是emmylua配置项非常多最好还是配置下, 当前最快的修复方法是在首个工作区内创建一个空的.emmyrc.json文件
> 
> 貌似还不行? 等会研究下

可以了，不能是空文件，必须有内容，内容为空配置 `{}` 即可。

**Comment by tinymins** [comment]
给项目都增加了空配置解决问题，不过有可能的话还是建议不增加空配置也能自动识别项目编码，易用性会高一些，再次感谢！

**Comment by tinymins** [comment]
> jx3dat

jx3dat 文件有些是 utf8 有些是 gbk ，这个类型文件是跟随游戏客户端的（ zhcn.jx3dat 是 gbk ，zhtw.jx3dat 是 utf8 ），我看看如何排除 utf8 的，感谢！

**Comment by tinymins** [comment]
> > > jx3dat
> > 
> > 
> > jx3dat 文件有些是 utf8 有些是 gbk ，这个类型文件是跟随游戏客户端的（ zhcn.jx3dat 是 gbk ，zhtw.jx3dat 是 utf8 ），我看看如何排除 utf8 的，感谢！
> 
> ![image](https://private-user-images.githubusercontent.com/40318218/344115880-52718931-261e-4c9d-af97-764bfdabe3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Njc3MzUsIm5iZiI6MTcxOTU2NzQzNSwicGF0aCI6Ii80MDMxODIxOC8zNDQxMTU4ODAtNTI3MTg5MzEtMjYxZS00YzlkLWFmOTctNzY0YmZkYWJlM2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA5MzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjgyZDQ1NzhlMjQxNzJmY2Y3YjJjZDZkYTM3NDYxMmMzY2ZmZjU2ZGE0M2VjNmFkMmE3Njc5MTZmNGZiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JglvYShzKKFFxHSKiQwK--oYJCZ2DW_N3k0DnTX5OdY) 可以在.emmyrc.json配置这个排除整个目录

请问下是如何看到报错的，我在 Output 里面没找到，因为我想试试 ignoreDir 是否支持通配符，其实所有 "*/data/" 目录都应该排除。

**Comment by CppCXY** [comment]
> 请问下是如何看到报错的，我在 Output 里面没找到，因为我想试试 ignoreDir 是否支持通配符，其实所有 "*/data/" 目录都应该排除。

不支持通配符, 因为这可能会有性能问题, 如果你想支持通配符可以考虑提交PR

**Comment by CppCXY** [comment]
> 不支持通配符, 因为这可能会有性能问题, 如果你想支持通配符可以考虑提交PR

项目地址:
https://github.com/CppCXY/EmmyLuaAnalyzer
