### ISSUE TITLE
总是提示expected whitespace indent, found 0 whitespace

### ISSUE THREAD

**Issue by remarxk** [EmmyLua/VSCode-EmmyLua#165]
我更新到了最新版本的emmylua，但我发现似乎emmylua不认识我的缩进符，我的每个换行他都有黄色波浪线警告，这是我做错了什么还是我应该做些什么配置去屏蔽掉这个显示的？

**Comment by CppCXY** [comment]
另外这个提示不是来自emmylua本体插件, 而是来自emmyluacodestyle插件

**Comment by remarxk** [comment]
感谢你的回复，我解决了这个问题
