### ISSUE TITLE
修改单个文件之后，diagnosing一直在运行

### ISSUE THREAD

**Issue by dreamcxy** [EmmyLua/VSCode-EmmyLua#173]
![image](https://github.com/user-attachments/assets/a61d1567-f90f-4089-a1fd-ad290acf70ba)
diagnosing能不能支持，多久运行一次，或者手动去执行，它现在是修改了单个文件的情况下，整个工程都会跑一遍

**Comment by CppCXY** [comment]
这不是emmylua的诊断, 这是luals的诊断, emmylua只会在启动时全局诊断
