### ISSUE TITLE
是否可以在已有的---@class上扩展方法

### ISSUE THREAD

**Issue by yish0000** [EmmyLua/VSCode-EmmyLua#174]
比如UWidget通过反射自动生成了注解
---@class UWidget
......

对于UWidget，可能项目内部额外手动实现了一个函数SetUserData，暴露到lua
这个手动实现的函数可否通过在另外一个文件中手写注解的方式使其增加到---@class UWidget的函数集中

**Comment by CppCXY** [comment]
需要原本生成时标记为`---@class (partial) UWdiget`, 这样在其他地方定义时也需要标记为partial

**Comment by yish0000** [comment]
感谢

**Comment by yish0000** [comment]
再请教个问题，class表实现了__call
local obj = class()
怎样写注解使obj匹配上class类型呢

**Comment by CppCXY** [comment]
---@class AAA
---@overload fun(): AAA
local MyClass

**Comment by yish0000** [comment]
好的，请问下，哪里有更完整的使用文档吗

**Comment by yish0000** [comment]
谢谢
