### ISSUE TITLE
关于只有打开过文件才能使Go to Definition 功能生效的问题。

### ISSUE THREAD

**Issue by gameronezz** [EmmyLua/VSCode-EmmyLua#18]
-- b.lua

local b = {}

function b:Test()

end

return b

-- a.lua

local b = require("b.lua")

b:Test()

a和b都在同一个文件夹下，在vscode中按照folder的形式打开的，如果我没有打开过b文件，则没有办法获得代码提示和Go To Definition功能。如果打开过了，这两个功能就好用了。

重启vscode过后，还得重新打开b文件，才能继续使用这两个功能。

其他的可能涉及到跨文件访问的功能还没有测使

IDEA上是OK的，vscode上是不支持吗？

VSCODE: Version: 1.32.3 (user setup)
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

EmmyLua 0.2.3

十分感谢！

**Comment by tangzx** [comment]
我这边不能重现，你把一个示例工程打包上传一下

**Comment by gameronezz** [comment]
我在做示例工程时候发现了。如果folder中均为.lua后缀，这些跨文件访问的功能是可以正常使用的。
我们所有的lua文件的后缀名都是.lua.txt，然后貌似emmylua就不识别了。
即使之前在vscode中偏好设置中将.txt后缀设置为了Lua语言也不好使。

不知道是否是vscode中配置的问题？
[TestProject.zip](https://github.com/EmmyLua/VSCode-EmmyLua/files/2976182/TestProject.zip)
