### ISSUE TITLE
Remote debugging?

### ISSUE THREAD

**Issue by iandol** [EmmyLua/VSCode-EmmyLua#180]
@CppCXY recommended I open a new issue from https://github.com/LuaLS/lua-language-server/issues/2951

In Zerobrane Studio Mobdebug works really well and is easy to setup (`luarocks install mobdebug` and turn remote server on in GUI, add these to script `md=require("mobdebug")` and then `md.start()`). I've previously used VSCode-Mobdebug, but it is not actively developed and is not stable. I've tried LuaHelper with LuaPanda but prefer to LuaLS. 

How can I setup remote debugging. I added the EmmyLua debug configurations, and also `require("emmy_core")` in my target lua script. But running "emmylua new Debug" I get this error:

<img width="254" alt="image" src="https://github.com/user-attachments/assets/debc52a3-0b60-42d0-a2a3-93739411968b">

The other debug config "Attach by Program" does not seem to support remote debugging?

My `require("emmy_core")` also fails, what is the procedure to install it?

macOS M2, latest VS Code, lua 5.4.7 and luarocks installed using homebrew

**Comment by CppCXY** [comment]
press: command + shift + p and search emmy:
![image](https://github.com/user-attachments/assets/9caca6b8-2da1-4124-887b-65a0f6c1a8cc)
this will insert some code like:
```lua
package.cpath = package.cpath .. ";c:/User/Path/to/emmy_core/?.dll"
local dbg = require("emmy_core")
dbg.tcpListen("localhost", 9966)
```
you can add more code for debug:
```lua
dbg.waitIDE()
dbg.breakHere()
```

You need to run the Lua script first and then run the debug configuration, or use a task to start the corresponding Lua program.

**Comment by iandol** [comment]
OK, that is working thanks! Will you accept a pull request with these instructions in case future users would like to get set up?

**Comment by CppCXY** [comment]
> OK, that is working thanks! Will you accept a pull request with these instructions in case future users would like to get set up?

Of course, if you are willing.

**Comment by iandol** [comment]
What is the difference between `dbg.waitIDE()` and `dbg.breakHere()`?

**Comment by CppCXY** [comment]
`dbg.waitIDE` means to pause execution and wait for the IDE to connect, `dbg.breakHere` means to force a break at this point.

**Comment by iandol** [comment]
So the first time we always need to use use `dbg.waitIDE`, then for subsequent breaks we only need `dbg.breakHere`?

**Comment by CppCXY** [comment]
> So the first time we always need to use use `dbg.waitIDE`, then for subsequent breaks we only need `dbg.breakHere`?

It's not like that, not all debugging needs involve debugging the startup code., it depends on the requirements. The EmmyLua debugger is non-blocking by default for this reason.

**Comment by iandol** [comment]
OK, but at least for remote debugging `dbg.waitIDE()` is always required? Anyway, see #181
