### ISSUE TITLE
卡在load lua 文件

### ISSUE THREAD

**Issue by djianxian** [EmmyLua/VSCode-EmmyLua#19]
一直卡在load lua 文件， 大概3秒一个文件，我的lua项目有1000多个lua文件，没法调试一次等他全部加载完，有一个报错不知道是不是这个原因导致，输出日志如下：
	[B]Symbol : 'udp_open'
	[B]Symbol : 'udp_strerror'
Found all necessary Lua functions [M:ulua.dll, V:510]
Debugger attached to process.
file not found:

        local function index(obj,name)        

        local meta=getmetatable(obj)

        local cached=meta.cache[name]        

        if cached then

           return cached

        else

           local value,isFunc = get_object_member(obj,name)

           if value==nil and type(isFunc)=='string' then error(isFunc,2) end

           if isFunc then

            meta.cache[name]=value

           end

           return value

         end

    end

    return index
file not found:chunk
file not found:        

        local rawget = rawget

        local rawset = rawset

        local getmetatable = getmetatable      

        local type = type  

        local function index(obj,name)  

            local o = obj            

            local meta = getmetatable(o)            

            local parent = meta

            local v = nil

            

            while meta~= nil do

                v = rawget(meta, name)

                

                if v~= nil then

                    if parent ~= meta then rawset(parent, name, v) end

                    local t = type(v)

                    if t == 'function' then                    

                        return v

                    else

                        local func = v[1]

                

                        if func ~= nil then

                            return func(obj)                         

                        end

                    end

                    break

                end

                

                meta = getmetatable(meta)

            end

           error('unknown member name '..name, 2)

           return nil	        

        end

        return index
file not found:

        local rawget = rawget

        local getmetatable = getmetatable   

        local rawset = rawset     

        local function newindex(obj, name, val)            

            local meta = getmetatable(obj)            

            local parent = meta

            local v = nil

            

            while meta~= nil do

                v = rawget(meta, name)

                

                if v~= nil then

                    if parent ~= meta then rawset(parent, name, v) end

                    local func = v[2]

                    if func ~= nil then                        

                        return func(obj, nil, val)                        

                    end

                    break

                end

                

                meta = getmetatable(meta)

            end  

       

            error('field or property '..name..' does not exist', 2)

            return nil		

        end

        return newindex
file not found:

        local rawget = rawget

        local getmetatable = getmetatable     

        local function call(obj, ...)

            local meta = getmetatable(obj)

            local fun = rawget(meta, 'New')

            

            if fun ~= nil then

                return fun(...)

            else

                error('unknow function __call',2)

            end

        end

        return call

    
file not found:

        local rawget = rawget                

        local getmetatable = getmetatable         

        local function indexEnum(obj,name)

            local v = rawget(obj, name)

            

            if v ~= nil then

                return v

            end

            local meta = getmetatable(obj)  

            local func = rawget(meta, name)            

            

            if func ~= nil then

                v = func()

                rawset(obj, name, v)

                return v

            else

                error('field '..name..' does not exist', 2)

            end

        end

        return indexEnum

    
load:F:/dingjie/client/fcity/Assets/Lua/System/Global.lua
load:System/Wrap.lua
load:System/class.lua
load:System/Math.lua
load:System/Layer.lua
load:System/CList.lua
load:System/Time.lua
load:System/Event.lua
load:System/Timer.lua
load:System/Vector3.lua
load:System/Vector2.lua
load:System/Quaternion.lua
load:System/Vector4.lua
load:System/Raycast.lua
load:System/Color.lua
load:System/Touch.lua
load:System/Ray.lua
load:System/Plane.lua
load:System/Bounds.lua
load:System/Coroutine.lua
load:System/List.lua
load:Common/define.lua
load:Common/functions.lua
load:Common/inspect.lua
load:System/Dictionary.lua
load:F:/dingjie/client/fcity/Assets/Lua/System/Main.lua
load:F:/dingjie/client/fcity/Assets/Lua/Startup.lua
load:GeneratedLua/CommonModule_pb.lua
load:GeneratedLua/Common_pb.lua
load:protobuf.lua
load:wire_format.lua
load:type_checkers.lua
load:encoder.lua
load:decoder.lua
load:listener.lua
load:containers.lua
load:descriptor.lua

**Comment by dj891116** [comment]
我试过，如果单独建一个只有lua的workspace 会快一些，但是如果包含unity所有文件夹的项目就很慢很慢
