### ISSUE TITLE
"Can't find Java!" on openjdk

### ISSUE THREAD

**Issue by ly-mg** [EmmyLua/VSCode-EmmyLua#23]
## Environment
- EmmyLua version: 0.2.5
- Java version: openjdk version "1.8.0_212-3-redhat"
- VSCode version: 1.33.1

## Error message
```
Can't find Java! Please install Java 1.8 or above and set JAVA_HOME environment variable.
```

## Related commit
"validate java" commit b7eb82669f6f30d02266e7d39117368b90c005b0

"src/extension.ts"
```
async function validateJava() {
...
            let regexp:RegExp = /java version "((\d+)\.(\d+).+?)"/g;
...
}
```

**This regexp will never match version string of openjdk.**

- `java -version` (RedHat openjdk) outputs:
  ```
  openjdk version "1.8.0_212-3-redhat"
  OpenJDK Runtime Environment (build 1.8.0_212-3-redhat-b04)
  OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
  ```

- `java -version` (Oracle Java SE) outputs:
  ```
  java version "1.8.0_212"
  Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
  Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
  ```

## about Java version information
[How to find the JVM version from a program?](https://stackoverflow.com/questions/5103121/how-to-find-the-jvm-version-from-a-program)

**Comment by ly-mg** [comment]
EmmyLua version 0.2.3 works correctly.

**Comment by tangzx** [comment]
Thanks for reporting. v0.2.6 released on marketplace.

**Comment by ly-mg** [comment]
v0.2.6 still says "Can't find Java!".

Version string of openjdk begins "openjdk version". (NOT "java version")

**Comment by Targanon** [comment]
getting Can't find Java! please install java or above and set JAVA_HOME environment variable.

I have check the version JAVA 'jre1.8.0_271' is installed.
but I"m not sure what I need to do to fix this.. I'm only new to VS code and Emmylua.. please help sort this so I can start learning lua..

**Comment by ChaosRifle** [comment]
getting this on vs code installation v0.5.14
