### ISSUE TITLE
v0.2.6 still says "Can't find Java!"

### ISSUE THREAD

**Issue by ly-mg** [EmmyLua/VSCode-EmmyLua#24]
Reopen issue #23.
I don't have permission to do.

**Comment by AriaLyy** [comment]
+1 ，osx 系统无法识别openjdk
![image](https://user-images.githubusercontent.com/10437293/62854518-22174980-bd22-11e9-9a76-04e8fd458409.png)

**Comment by ly-mg** [comment]
v0.3.28
It looks to work fine.

**Comment by fdcumt** [comment]
it still not work on v0.3.28

**Comment by zengjinji** [comment]
relate https://github.com/EmmyLua/VSCode-EmmyLua/issues/40

**Comment by appgurueu** [comment]
Still not working

**Comment by gvol1222** [comment]
Solved it in windows by pointing at C:\Program Files\Java\jdk-15.0.1 at settings.json. The default path is set C:\Program Files\Common Files\Oracle\Java\javapath when installing. Below the added line at settings.json: 
`"emmylua.java.home": "C:\\Program Files\\Java\\jdk-15.0.1"`

**Comment by ly-mg** [comment]
> Solved it in windows by pointing at C:\Program Files\Java\jdk-15.0.1 at settings.json. The default path is set C:\Program Files\Common Files\Oracle\Java\javapath when installing. Below the added line at settings.json:
> `"emmylua.java.home": "C:\\Program Files\\Java\\jdk-15.0.1"`

Thank you for your information.
