### ISSUE TITLE
Step over F10 not working as intended

### ISSUE THREAD

**Issue by phansonloc1999** [EmmyLua/VSCode-EmmyLua#26]
I'm using EmmyLua with LOVE2D and not sure if this is a new feature or not. But when i put a breakpoint and then hit F10, the debugger doesn't move to next statement but instead goes back to that breakpoint on the next frame (similar to F5). I had to manually set continuous breakpoints as a workaround to debug next statements.

**Comment by phansonloc1999** [comment]
F11 works like F10 now. I'm confused
![image](https://user-images.githubusercontent.com/31174158/59552557-b67b5f00-8fb2-11e9-820f-dc007fa8311c.png)

**Comment by tangzx** [comment]
All issues about debugger will be ignored. Since the debugger is unstable and many bugs, it has been deprecated, and a new debugger is being rewritten. See here https://github.com/EmmyLua/EmmyLuaDebugger
