### ISSUE TITLE
java.exe 占用内存2G，有点太大了

### ISSUE THREAD

**Issue by iNeverSleeeeep** [EmmyLua/VSCode-EmmyLua#27]
rt

**Comment by najoast** [comment]
![image](https://user-images.githubusercontent.com/14048531/80567405-b009a080-8a27-11ea-8133-c22b788d1064.png)
我的占了2.6G，这插件确实太吃内存了。

关掉vscode后java进程就没了，确实是这个插件导致的。

**Comment by najoast** [comment]
主要是解析大文件导致的，像我这边有个 lua 文件 2M 多，这一个就占了1G多。如果用 IDEA 的 emmylua，有个选项可以过滤大文件的加载 ( Too larger file threshold )，可以配置超过多大就不加载了。但 vscode 没有这个选项。且我认为这个解决方案不如 gitignore 的方案好。但目前连大文件过滤都没有，gitignore 方案就更不可能提供了。
