### ISSUE TITLE
希望可以增加require路径提示

### ISSUE THREAD

**Issue by qcbf** [EmmyLua/VSCode-EmmyLua#28]
希望可以增加require路径提示
谢谢.

**Comment by luoyxy** [comment]
找到一种曲线实现的方法

**Comment by luoyxy** [comment]
找到一种 通过别名+字符常量注释 曲线实现的方法
声明一个 require 同名的方法 纯粹为了提示用
自己再写个工具生成一个单独的lua文件  声明别名requirMod 
---@alias requirMod string|'"Common"'|'"Dispatcher"'|
requirecache = require
---@param modname requirMod
function require(modname)
end
require = requirecache
