### ISSUE TITLE
How to disable underline?

### ISSUE THREAD

**Issue by dandevs** [EmmyLua/VSCode-EmmyLua#29]

**Comment by qcbf** [comment]
+1

**Comment by najoast** [comment]
* Open `~/.vscode/extensions/tangzx.emmylua-0.3.49/out/annotator.js`
* Delete this line: `D_UPVALUE = createDecoration("", { textDecoration: "underline" });`

More detail (in Chinese): https://github.com/EmmyLua/VSCode-EmmyLua/issues/59

**Comment by CppCXY** [comment]
now support this
