### ISSUE TITLE
Option to ignore subdirectories

### ISSUE THREAD

**Issue by dlbd** [EmmyLua/VSCode-EmmyLua#31]
Hi,
Is it possible to have EmmyLua ignore (don't parse) certain directories? In my project  I have an `out/` directory with bundled and/or minified code. Sometimes "go to definition (F12)" goes to the built .lua files instead of actual sources, and type annotations don't update until I rebuild the bundles.

**Comment by winterwolf** [comment]
Just don't add them to workspace! Create your project in empty directory and then add directories with your sources:

![screenshot-001](https://user-images.githubusercontent.com/42620439/74689243-1fbb0e00-51e3-11ea-81bc-c8ef191581d0.png)
