### ISSUE TITLE
Support for LuaJIT number types

### ISSUE THREAD

**Issue by avkapustin** [EmmyLua/VSCode-EmmyLua#37]
As mentioned in [this issue](https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/272), please add support for number suffixes LL/ULL

**Comment by tangzx** [comment]
Fixed, please try the latest build https://ci.appveyor.com/project/EmmyLua/vscode-emmylua/build/artifacts

**Comment by avkapustin** [comment]
Thank you, looks like all numbers are now parsed ok.
P.S. It seems what this new build (0.3.33) hangs on some lua files in my project, I'll try to reproduce it or find some logs. But this is unrelated to this concrete issue...
