### ISSUE TITLE
v0.3.28 can`t find java

### ISSUE THREAD

**Issue by fdcumt** [EmmyLua/VSCode-EmmyLua#40]
v0.3.28 can`t find java

**Comment by fdcumt** [comment]
vscode version 1.39.2

**Comment by zengjinji** [comment]
vscode 1.40.0
emmylua  v0.3.28 


开发环境 mac， vscode远程链接到debian9 上
安装emmylua on ssh
emmylua 报错 Can't find Java! Please install Java 1.8 or above and set JAVA_HOME environment variable.

在debian 上执行java 可以找的到
```
root@xxx:~# java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
root@xxx:~# javac -version
javac 1.8.0_232
root@xxx:~# sudo update-alternatives --config java
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Nothing to configure.
rroot@xxx:~# echo $JAVA_HOME
/usr/bin/java
```

**Comment by zengjinji** [comment]
问题补充说明：
在settings.json  中 增加配置"emmylua.java.home": "/usr/bin/java" 也无法铡刀

**Comment by zengjinji** [comment]
补充说明：vscode 在ssh远程开发时，安装golang 插件的时候也出现过这个问题，原因是
1.我的这台机器在初始化安装会在/etc/profile.d/bash_profile.sh  这个目录下 默认写了一个 EXport $GOROOT = /opt/go，但是实际上这个/opt/go 并没有安装
2.我实际上安装的是/usr/local/go，并且在 /etc/profile 上写了 EXport $GOROOT = /usr/local/go
3.vscode远程登陆时，里面的终端的运行 echo $GOROOT是对的，但是golang插件运行一直提示/opt/go 没找到

猜测是vscode 的插件加载的环境变量和终端不一样，可以在插件报找不到JAVA 时，把$JAVA_HOME 这个变量输出到vscode 的问题框里面吗？ 这样可能有助于排查问题 或者我能从日志还是哪里看到emmylua 这个插件实际加载的$JAVA_HOME 变量值
