### ISSUE TITLE
0.3.36版本打开 lua 文件时一直卡在 Emmy parse fail

### ISSUE THREAD

**Issue by deckvig** [EmmyLua/VSCode-EmmyLua#43]
* Linux
升级到 ci 最新版本后遇到插件不工作问题，lua 文件打开后插件一直在 parse 同一个文件,使用商城最新版时时 ok 的
![image](https://user-images.githubusercontent.com/15033627/69899591-98a88780-13a3-11ea-9bf2-68437d2d5c5c.png)
![image](https://user-images.githubusercontent.com/15033627/69899594-a100c280-13a3-11ea-950d-6a95c80ad609.png)

```
Nov 30, 2019 6:56:46 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 46
```

**Comment by deckvig** [comment]
使用最新版 Emmy-Language 解决

**Comment by SilhouettesForYou** [comment]
您好，我是在Windows下的VS Code，怎么没有找到最新的Emmy-Language-Server

**Comment by CppCXY** [comment]
> 

vscode 当前的ls是内置最新的
