### ISSUE TITLE
0.3.33及以上版本不能在unbuntu里运行

### ISSUE THREAD

**Issue by sysuxiaom** [EmmyLua/VSCode-EmmyLua#46]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
…

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
具体什么问题？

**Comment by code3p** [comment]
0.3.6版本在Mac上运行时parse file在第一个文件就卡住了。

org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
警告: Unmatched cancel notification for request id 3

**Comment by sysuxiaom** [comment]
parse file在第一个文件就卡住了。

发送自 Windows 10 版邮件应用

发件人: 阿唐
发送时间: 2019年12月19日 14:30
收件人: EmmyLua/VSCode-EmmyLua
抄送: sysuxiaom; Author
主题: Re: [EmmyLua/VSCode-EmmyLua] 0.3.33及以上版本不能在unbuntu里运行 (#46)

具体什么问题？
