### ISSUE TITLE
Configure indentation

### ISSUE THREAD

**Issue by Gjum** [EmmyLua/VSCode-EmmyLua#57]
EmmyLua ignores VSCode's indentation settings, as well as [.editorconfig](https://editorconfig.org/).
I am unable to select the indentation that is required for the project.

**What I expect:** When running "Format Document" action, EmmyLua should format the file with the configured indentation (tabs).

**What happens:** The file is formatted using 4 spaces as indentation.

**Details**

My `settings.json:
```json
    "[lua]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": false,
        "editor.defaultFormatter": "tangzx.emmylua"
    },
```

Selected indentation on the edited .lua file is `Tab Size: 2`

My `.editorconfig`:
```ini
root = true

[*]
indent_style = tab
indent_size = 2
```

**Comment by ronaldoooo** [comment]
+1

**Comment by cooltrooper** [comment]
+1

**Comment by mauricebauer** [comment]
Maybe this helps for someone who could implement this:

- The JavaScript library ``lua-fmt`` is used to format lua code with this extension
- ``lua-fmt`` accepts and options-object for the ``formatText(...)``-method
- There we can pass ``indentCount`` and ``useTabs``

So I think the only work to be done is to get the correct indentation setting from VSCode and provide this information to the ``lua-fmt.formatText(...)`` in the ``extension.ts`` file of this extension here.

Looking forward for someone who could finish this idea 😄
