### ISSUE TITLE
希望 upvalue 下划线能开出去配置

### ISSUE THREAD

**Issue by najoast** [EmmyLua/VSCode-EmmyLua#59]
现在默认都是开着的，很影响代码的美观度，希望能开出个配置来控制。

```js
// annotator.js
function updateDecorations() {
    D_PARAM = createDecoration("colors.parameter");
    D_GLOBAL = createDecoration("colors.global");
    D_DOC_TYPE = createDecoration("colors.doc_type");
    D_UPVALUE = createDecoration("", { textDecoration: "underline" });
}
```

**Comment by najoast** [comment]
希望上面4个影响观感的几个配置，默认都能关掉。

emmylua.colors. parameter = "",
emmylua.colors. global = "",
emmylua.colors. doc_type = "",
emmylua.text_docoration.upvalue_underline = false,

我的想法是，大家在用 emmylua 之前，都有自己喜欢和习惯的 theme， 变量、函数是什么颜色经过长时间的适应已经习惯了，如果 emmylua 强制带入自己的配色，会给用户带来不必要的困扰，甚至因为颜色的改变而影响阅读代码的效率。

所以 emmylua 做为一个调试、静态分析插件，更多的从功能性上满足大家，至于配色，尽量不去影响用户的使用习惯。

所以建议默认关掉，开出这些配置让想用的人自己打开。

***
当然了，如果 emmylua 的老用户已经习惯了这些颜色，那也可以保留，我们这些新用户自己去关也没问题。

**Comment by IULOVE** [comment]
确实··不应该改默认的配色··搞的好不习惯，希望有个可以控制开关的

**Comment by najoast** [comment]
> 确实··不应该改默认的配色··搞的好不习惯，希望有个可以控制开关的

颜色是有开关的，在 vscode 配置里加上下面这些配置就可以了:
```
emmylua.colors. parameter = "",
emmylua.colors. global = "",
emmylua.colors. doc_type = "",
```

**Comment by najoast** [comment]
既然没人处理，就关掉了。
