### ISSUE TITLE
Change pink syntax highlighting of global variables to underlines

### ISSUE THREAD

**Issue by migmoog** [EmmyLua/VSCode-EmmyLua#64]
The pink colors can interfere with colors schemes people already have, so to mark global functions/variables perhaps they could be changed to underlines rather than changing their color to pink. It can get especially confusing for people have themes like monokai 
![image](https://user-images.githubusercontent.com/57271984/89803060-56be0c80-db00-11ea-860d-635aa60bdde0.png)

**Comment by bbassie** [comment]
@mig-moog If you didn't know yet, in the settings you can change the global color. See Issue #12 
(more like a temporary workaround for you)

**Comment by winterwolf** [comment]
Underlines already used to highlight variable from different scope.

![screenshot-001](https://user-images.githubusercontent.com/42620439/93149274-8e6f3400-f6fe-11ea-86ae-a0a85ad00c54.png)
