### ISSUE TITLE
 EmmyLua Attach Debug -> 选择对应Unity进程 我在选择unity进程时，一个进程都没显示，不能选择

### ISSUE THREAD

**Issue by 2296810189** [EmmyLua/VSCode-EmmyLua#67]
![image](https://user-images.githubusercontent.com/70999539/92561779-6a979280-f2a7-11ea-9f86-757dda28bf3e.png)

**Comment by tangzx** [comment]
去群里下最新的0.3.55版本试试

**Comment by 2296810189** [comment]
我这里显示最新的是0.3.49，群里？有地址吗
