### ISSUE TITLE
Number keys cannot be described as fields?

### ISSUE THREAD

**Issue by winterwolf** [EmmyLua/VSCode-EmmyLua#68]
![screenshot-001](https://user-images.githubusercontent.com/42620439/93149865-3a654f00-f700-11ea-91db-b9dce340101d.png)

You know, tables are not objects. There are no restrictions on use numbers as keys. Sometimes I want to combine the functionality of an object and an array in one table.

... Also I have no idea how to correctly describe varargs like in this example. Please help! 😓️

**Comment by thorlucas** [comment]
I am also wondering this.

**Comment by CppCXY** [comment]
now fix
