### ISSUE TITLE
How to use debugger in vscode

### ISSUE THREAD

**Issue by phansonloc1999** [EmmyLua/VSCode-EmmyLua#7]
I'm new to Emmylua and have no idea how remote or attach debug works. Do i need mobdebug.lua in my source files for debugger to work? There are instructions for IntelliJ but not for vscode :(

**Comment by tangzx** [comment]
`vscode-emmylua` only supports debugging in windows for now. (remote debugger supports cross-platform but doesn't work now)
![image](https://user-images.githubusercontent.com/3354360/47057433-4209d980-d1f3-11e8-9251-86f847f558e1.png)
![image](https://user-images.githubusercontent.com/3354360/47057486-901edd00-d1f3-11e8-91db-0bd7cf36ea00.png)
![image](https://user-images.githubusercontent.com/3354360/47057559-d7a56900-d1f3-11e8-8173-abeff9a26c9c.png)
![image](https://user-images.githubusercontent.com/3354360/47057580-f0ae1a00-d1f3-11e8-8841-db58120a738d.png)
