### ISSUE TITLE
使用C#+Unity时用VSCode来写lua，安装这个插件后提示我没JAVA环境，Can't find Java! Please install Java 1.8 or above and set JAVA_HOME environment variable.

### ISSUE THREAD

**Issue by YvHao** [EmmyLua/VSCode-EmmyLua#72]
Can't find Java! Please install Java 1.8 or above and set JAVA_HOME environment variable.
这个怎么解决，为了这个插件去安一个嘛。。。这个插件是不是必须要java环境啊，有没有大神帮我解答一下

**Comment by gvol1222** [comment]
Solved it in windows by pointing at C:\Program Files\Java\jdk-15.0.1 at settings.json. The default path is set C:\Program Files\Common Files\Oracle\Java\javapath when installing. Below the added line at settings.json:
"emmylua.java.home": "C:\\Program Files\\Java\\jdk-15.0.1"

**Comment by hugebug4ever** [comment]
> Can't find Java! Please install Java 1.8 or above and set JAVA_HOME environment variable.
> 这个怎么解决，为了这个插件去安一个嘛。。。这个插件是不是必须要java环境啊，有没有大神帮我解答一下

 对，需要设置 JAVA_HOME 环境, 或者 如 @gvol1222  所述，在  setting 里设置。可以设置相对目录，让项目组共享一份 Java。
