### ISSUE TITLE
可以提供忽略指定文件的配置么

### ISSUE THREAD

**Issue by mrziplee** [EmmyLua/VSCode-EmmyLua#79]
有时候配置太大, java 解析时cpu/内存拉满了...当然我们也可以拆分文件, 不过也希望能有个忽略的配置, 谢谢大佬

**Comment by CppCXY** [comment]
自己在工作区根目录新建emmy.config.json 文件，然后写
{
    "source": [
        {
            "dir": "./",
            "exclude": [
                "csv/**.lua"
            ]
        }
    ]
}

**Comment by mrziplee** [comment]
谢谢大佬
