### ISSUE TITLE
for ... do 下面第一句代码无法通过@type制定类型

### ISSUE THREAD

**Issue by Weiged** [EmmyLua/VSCode-EmmyLua#8]
![db2df53394d82f15ddecea7268b85d2d](https://user-images.githubusercontent.com/41810718/47693214-b866fc80-dc33-11e8-8858-04b70cd2e83f.png)
这种情况下，b能看出类型，a不能
![29767a19586d6d5b80d8aeb030aa37fc](https://user-images.githubusercontent.com/41810718/47693224-c7e64580-dc33-11e8-8829-9a653f08ac9a.jpg)

测试发现只要在a上面加一句其他代码，a就能制定类型了

**Comment by tangzx** [comment]
已修复
