### ISSUE TITLE
能否无侵入的为第三方lua代码添加注解

### ISSUE THREAD

**Issue by fomiao** [EmmyLua/VSCode-EmmyLua#84]
由于第三方代码需要频繁更新，不希望修改他们的代码

**Comment by CppCXY** [comment]
自己创建一个目录写一些不会被使用的文件比如叫http.d.lua 在里面写注释类
---@class ffff
local ffff = {}
function ffff:aaaa()
end
就行了

**Comment by fomiao** [comment]
> 自己创建一个目录写一些不会被使用的文件比如叫http.d.lua 在里面写注释类 ---@Class ffff local ffff = {} function ffff:aaaa() end 就行了

虽然上面说的是可以的，但是有相当工作量和维护量，如果可以如下声明就方便多了（声明后会吧helper返回的table定义为Helper类）
---@class Helper
local M = require "3d_party.helper"
