### ISSUE TITLE
vscode emmylua调试-定位文件错误

### ISSUE THREAD

**Issue by lualcs** [EmmyLua/VSCode-EmmyLua#86]
环境
vscode emylua   安装时qq群里面的emmylua 插件v0.3.103
emmylua_new 
程序
skynet 

表现
因为有大量重复的不同模块但是-同名文件
堆栈显示断点路径是正确的
vscode 没有正确定位到文件

**Comment by lualcs** [comment]
请下载 https://gitee.com/luo-changshuang/new-skynet.git 
这个代码 可以重现问题 写了一个小demo

启动 命令 ./skynet emmyluaDebugError/config

**Comment by mlzzen** [comment]
我也遇到了类似的问题，不过暂时没发现触发规则。我看项目里面也没有相同的Control.lua，也没在Control.lua打断点。
![image](https://github.com/EmmyLua/VSCode-EmmyLua/assets/11664505/82e9bfe0-5b45-499e-be80-e74e0fd51121)

**Comment by CppCXY** [comment]
有问题进群交流, 在这里发issue我很可能看不到. skynet得官方调试器是lua-debug最好用那个. 多文件同名问题是因为emmylua在根据chunkname判断命中之后会把当前chunkname下发给vscode, vscode插件端用他的find接口查找文件, 找到哪个就是哪个.
解决办法: 想办法让chunkname足够长, 长到不同文件出现区分.



> 我也遇到了类似的问题，不过暂时没发现触发规则。我看项目里面也没有相同的Control.lua，也没在Control.lua打断点。 

BUG就进群反馈

**Comment by yefansky** [comment]
我修改了，正在等待合并
