### ISSUE TITLE
Ctrl+鼠标左键，对表(table)成员跳转（转到定义）问题

### ISSUE THREAD

**Issue by wisz** [EmmyLua/VSCode-EmmyLua#9]
例如：
testTime = {}
testTime .__index = testTime

function testTime :ShowData()
   ....
end

假如上面的代码保存在a.lua
我在别的文件中：
OperateData是testTime的一个实例
OperateData:ShowData()
这句代码，按住Ctrl键，然后鼠标在ShowData上点击以实现跳转，但是在VSCode里没有反映，在Interllij里是可以的。

**Comment by tangzx** [comment]
不够具体，最好提供两个文件。

**Comment by wisz** [comment]
[test.zip](https://github.com/EmmyLua/VSCode-EmmyLua/files/2697926/test.zip)
看b.lua文件。

**Comment by tangzx** [comment]
我这正常，可能是版本问题。改天发个新的。
