### ISSUE TITLE
0.4.9 最新版

### ISSUE THREAD

**Issue by foreversos** [EmmyLua/VSCode-EmmyLua#92]
打开VSCODE之后,等待EMMYLUA解析完毕
然后能够再VSCODE里面看到方法变量符号
但是使用self.无法跳出补全....
不知道怎么排查和解决

**Comment by CppCXY** [comment]
解析完毕之后会执行代码诊断，这部分没有显示出来（以前是一边解析一遍诊断）。由于增加了许多检查所以诊断越来越慢，在默认选项下影响最大的就是deprecated诊断，所以该特性已经被移除了，最新(0.4.10)的更新已经将诊断移到另一个线程不会影响当前的补全了。

**Comment by foreversos** [comment]
OK...现在就是耐心等待官方市场更新对吧?
