### ISSUE TITLE
VSCODE EMMLUA 只有使用@class注解才支持使用self

### ISSUE THREAD

**Issue by foreversos** [EmmyLua/VSCode-EmmyLua#97]
使用的quickCOCOS之前的类构建
![image](https://user-images.githubusercontent.com/3012313/162679578-44bc8f00-5fd8-4cdf-82ed-47d65cd9edd2.png)

之前几次都是不能使用self. 弹出提示
今天测试加上注解class就可以了
那有没方法不加就能使用?(仅限本类变量方法就够用了)

**Comment by CppCXY** [comment]
一个正确使用得模板是
```
local c = class(...)

function c:xxxx()
end
```
是可以不加`---@class`的

**Comment by foreversos** [comment]
嗯.但是我自己的工程做了测试,还是解决不了...
我先用注解能正常,移除就不正常,都是简单的测试类
![Code_LAYsqjxWD7](https://user-images.githubusercontent.com/3012313/162685006-54bccb23-b08e-4174-967c-f8a6689e952d.gif)

**Comment by CppCXY** [comment]
你完全新开一个工作区，以该工作区打开vscode创建一个简单文件，然后试试看

**Comment by CppCXY** [comment]
我怀疑是因为class返回的表被识别为同一个类，于是self.会从所有文件来找出补全,于是就卡住了

**Comment by CppCXY** [comment]
你可以给class 函数一个注解 ---@return any

**Comment by foreversos** [comment]
好的,我试试.
应该是我的工程问题,否则这种问题很多人早就发现了
谢谢解答
现在能用用class也够用

**Comment by foreversos** [comment]
测试@retrurn 仍然不行
以下是我这边的class方法

---@return any
function class(classname, ...)
    local cls = {
        __classname = classname,
        __isClass = true,
        getClassName = function(self)
            return self.__classname
        end
    }

    local supers = {...}
    for _, super in ipairs(supers) do
        local superType = type(super)
        -- assert(
        --     superType == "nil" or superType == "table" or superType == "function",
        --     string.format('class() - create class "%s" with invalid super class type "%s"', classname, superType)
        -- )

        if superType == "function" then
            -- assert(
            --     cls.__create == nil,
            --     string.format('class() - create class "%s" with more than one creating function', classname)
            -- )
            -- if super is function, set it to __create
            cls.__create = super
        elseif superType == "table" then
            if super[".isclass"] then
                cls.__create = function()
                    return super:create()
                end
            else
                -- super is pure lua class
                cls.__supers = cls.__supers or {}
                cls.__supers[#cls.__supers + 1] = super
                if not cls.super then
                    -- set first super pure lua class as class.super
                    cls.super = super
                end
            end
        else
            error(string.format('class() - create class "%s" with invalid super type', classname), 0)
        end
    end

    cls.__index = cls

    if not cls.__supers or #cls.__supers == 1 then
        setmetatable(cls, {__index = cls.super})
    else
        setmetatable(
            cls,
            {
                __index = function(_, key)
                    local supers = cls.__supers
                    for i = 1, #supers do
                        local super = supers[i]
                        if super[key] then
                            return super[key]
                        end
                    end
                end
            }
        )
    end

    if not cls.ctor then
        -- add default constructor
        cls.ctor = function()
        end
    end
    cls.new = function(...)
        local instance
        if cls.__create then
            instance = cls.__create(...)
        else
            instance = {}
        end
        setmetatableindex(instance, cls)
        instance.class = cls
        instance:ctor(...)
        return instance
    end
    cls.create = function(_, ...)
        return cls.new(...)
    end
    
    return cls
end

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/162688140-9d3ac2d7-4ec7-4c0c-a884-a7a1ff49aa6d.png)
看起来很正常

**Comment by foreversos** [comment]
好的,应该是我工程其他文件有很多不规范写法,把这个相关搞分析的弄坏了.
暂时不折腾了,感谢~
